version: '3.3'
services:
  client:
    environment:
      - GET_HOSTS_FROM=dns
    image: "scaleoutsystems/mnist-client-pytorch:latest"
    build:
      context: .
    working_dir: /app
    command: /bin/bash -c "fedn run client -in client.yaml"
    volumes:
      - ./data:/app/data:ro #mount as READ ONLY
      - ./client.yaml:/app/client.yaml
